limit_req_zone $remote_addr zone=api:10m rate=100r/s;
limit_req_zone $remote_addr zone=face:10m rate=50r/s;

upstream backend_api {
    server blue_backend:4000;
}

upstream face_service {
    server blue_face:5001;
}

upstream frontend_service {
    server blue_frontend:80;
}

server {
    listen 80;
    server_name localhost attendance-ml.duckdns.org;

    location /api/ {
        limit_req zone=api burst=20 nodelay;
        proxy_pass http://backend_api;
    }

    location /face/ {
        limit_req zone=face burst=10 nodelay;
        proxy_pass http://face_service;
    }

    location /moodle/ {
        proxy_pass http://moodle:80/;
    }

    location / {
        proxy_pass http://frontend_service;
    }
}
